### ISSUE TITLE
Fix multiple selection width/length 

### ISSUE THREAD

**Issue by Vino4** [lightertu/TeamDivider#30]
Problem is present in [Dashboard's Survey Info Form] and [Activity's Search Bar].
The field expands and stretches out of place. The plan is to make it have a fixed width and go longer in [Activity's Search Bar] similar to [Dashboard's Survey Info Form].  [Dashboard's Survey Info Form] needs it's modal to with with scrolling.

**Comment by Lebonesco** [comment]
I fixed the width in Activities

**Comment by lightertu** [comment]
this one goes to Joseph.
