### ISSUE TITLE
Complete Hooking Dashboard up to the Backend

### ISSUE THREAD

**Issue by Vino4** [lightertu/TeamDivider#39]
All the changes to the Survey Section need to be done to the Dashboard Section.

**Comment by Vino4** [comment]
This is not fully complete. We still need to hook up the account setting, side bar and nav bar as well as Survey Previews and Survey links activities.

**Comment by lightertu** [comment]
@Vino4 Is it done now?

**Comment by Vino4** [comment]
It's been done for three days now (with the exception of Account Settings which we have to forget about because there is no time for it) .. i'm holding off on updating issues atm becuase i need to get everything working ASAP. Last remaining item is the Activity. Once i'm done with it i'll update all the issues.

**Comment by lightertu** [comment]
bravo
