### ISSUE TITLE
being able to delete paratitipants

### ISSUE THREAD

**Issue by Vino4** [lightertu/TeamDivider#49]
Many things need to be done here
on Activities, Trash area where drop marks for delete.
Backend functionality needs to support that
Both @Lebonesco and @kaih1994 have a steam in this.

**Comment by Lebonesco** [comment]
@Vino4 do you want me to handle the UI for this?
I know how to hook into Rui's DnD functions.

**Comment by Vino4** [comment]
@Lebonesco That would be great!
I think it's the most efficient if you own this issue :)

**Comment by Lebonesco** [comment]
@Vino4 what do you want me to send to the API?

**Comment by Vino4** [comment]
That would need the expert opinion of @kaih1994 , I haven't touched the participant API yet!
We're meeting today at 5, i'll update this as soon as i know :)

**Comment by Lebonesco** [comment]
I was thinking that an easy way to do would be to simply change their group to another negative value like when they are in the left column.

**Comment by Vino4** [comment]
Gotcha! That sounds smooth, i'll let @kaih1994 know!

**Comment by kaih1994** [comment]
I wil update the API to accept (-1)
PUT   https://{server_addr}/api/activities/:activity_id/participants/:participant_id/groupNumber

Payload:
```
{
groupNumber: -1
}
```

**Comment by Lebonesco** [comment]
finished with basic user deletion

**Comment by Lebonesco** [comment]
I'm going to close this issue. You don't need to create any new endpoints. Users will be in group -2.

**Comment by Vino4** [comment]
@Lebonesco I believe Kai was saying that becuase the backend used to only accept non-negative numbers. Putting people in group -2 will require a change in the backend to accept that.
I think they should be put in group -1 becuase @kaih1994 already made this change :)
Note: if you're using -1 for something else then Kai needs to know so that he can allow the API to accept -2

**Comment by Lebonesco** [comment]
-1 has always been reserved for people in the side bar

**Comment by Vino4** [comment]
@Lebonesco cool
in that case, @kaih1994 needs to minimum limit everywhere where we have a minimum group index of 0.

**Comment by kaih1994** [comment]
I have set the backend to accept -2 && -1 && >0 GroupNumber when updating participant's groupNumber.

But should I set the default GroupNumber for every new participant to -1 or -2?

**Comment by Vino4** [comment]
@kaih1994 the default should be -1 (sidebar). -2 is deleted.

**Comment by kaih1994** [comment]
good. there will be no change to code in model.
