### ISSUE TITLE
Locking groups

### ISSUE THREAD

**Issue by Vino4** [lightertu/TeamDivider#50]
This one is  alot of work.
- Lock groups functionality, mark them on the back end as well so that the algorithm doesn't re-arrange them. The work so far is saved and the algorithm can be used again.
- Icons on Activity page need to be made.
- Actions and Action Handlers need to be implemented.

If we can get this done, that would be a huge win. This is what Stewart is looking for.

@kaih1994 Lots of API left work here

**Comment by Vino4** [comment]
We currently do not have a data-structure for the groups. ~~A lock status needs to be place in each participant~~ https://github.com/lightertu/TeamDivider/issues/50#issuecomment-304738059 . Lock API should deal with that. @kaih1994 This change needs to be introduced in the Participant Schema

**Comment by Lebonesco** [comment]
I'm can do the client side work.

**Comment by Vino4** [comment]
@Lebonesco That's awesome.
I'll put this here for documentation:
Based on a our recent WeChat convo, we decided that it is better to put a Boolean Array of Group Numbers in the Activity Schema to represent the locks.

**Comment by Lebonesco** [comment]
@Vino4 I just finished the front end and redux stores based around an array of bools.

**Comment by Vino4** [comment]
@Lebonesco That was quick! Thanks boss.
@kaih1994 The rest is on you brother

**Comment by kaih1994** [comment]
I will do that.  (^_^)

**Comment by kaih1994** [comment]
@Vino4 @Lebonesco I am now working on that. But I need to know your guys' thought of the design . So, how does backEnd know par1, par2,... need to be locked? 
build a new API to lock them? 
What should the payload look like?

**Comment by kaih1994** [comment]
I am done with that. The new api is 
```
POST https://{server_addr}/api/activities/:activity_id/lockedGroup/

DELETE https://{server_addr}/api/activities/:activity_id/unlockedGroup/:groupNumber
```
The payload for post is 
```
{
	"groupNumber": 3 // or other number you want, but groupNumber should be >= -2, remember it
}
```

**Comment by lightertu** [comment]
@kaih1994 Is backend ready to support this?

**Comment by kaih1994** [comment]
Yeah.

**Comment by lightertu** [comment]
Good job everyone
