### ISSUE TITLE
Allow users to changed group capacity

### ISSUE THREAD

**Issue by Vino4** [lightertu/TeamDivider#56]
More leg work for @kaih1994 here

**Comment by kaih1994** [comment]
in the back end, it is in the payload. 
PUT    https://{server_addr}/api/activities/:activity_id

```
{ "name": req.body.name,

"endDate": new Date(req.body.endDate),

 "totalCapacity": req.body.totalCapacity,

 "groupCapacity": req.body.groupCapacity,}
```

**Comment by lightertu** [comment]
I believe this can be done with the current back-end

**Comment by Vino4** [comment]
It was here for the front end as well but it's implemented now
