### ISSUE TITLE
Parsing Axios errors.

### ISSUE THREAD

**Issue by Vino4** [lightertu/TeamDivider#60]
Axios returns the response in .response.data, our API returns the error in .data.error.
The way to read Errors is to access [error.response.data.error] inside the .catch of an Axios response.
@Lebonesco and @Vino4 need to get their shit together. @lightertu and @kaih1994 did it the "right way" :rofl:

**Comment by Lebonesco** [comment]
That's because the back end messed up in the beginning and didn't implement it. Then they did and didn't tell anyone. This isn't addressing the bigger issue that no errors should be returning. I still don't know what you guys changed to make the connection fail.

**Comment by Vino4** [comment]
@Lebonesco Lol yea but it's okay coz now we know what's going on. As for the "no errors should be returning", the backend added a lot of input validation to make sure nothing blows-up in the database rather than throwing everything and having different components use the same tables differently (i.e. i didn't know about the -1 being reserved for sidebar, i could a broke things when i messed with group numbers but @kaih1994 input validation helped me learn that). So now, by updating our corresponding axios error logging we can tell exactly when the request failed and that'll help us either change the payload to fit the requirements or change the requirements to fit the payload (based on our design). Like, one of the reasons when your update request failed is probably because the API didn't use to allow -1, now it does. But it still doesn't allow -2 so it'll likely fail. Getting the errors will help us locate all of those inconsistencies :)

**Comment by Vino4** [comment]
BTW i updated all of mine so once you update yours feel free to close this :smiley:

**Comment by Lebonesco** [comment]
you updated the axios parsing?

**Comment by Vino4** [comment]
I think it's more accurate to say our error logging. I dunno what i keep coming up with vague ways to describe without fail haha (although i think the fact that i wrote most of these at 3 AM helps xD). It's a simple fix, just access [error.response.data.error] in catch rather than just error :)
