### ISSUE TITLE
Run the Algorithim API

### ISSUE THREAD

**Issue by Vino4** [lightertu/TeamDivider#61]
We need the API to run the algorithm to be done ASAP. @kaih1994

**Comment by Vino4** [comment]
We also need this to work with arbitrary arrays of strings. @Lebonesco has done most of the legwork on his front end [name yet to be decided] matching technology. @kaih1994 could use that abstraction instead of having to rewrite it.

**Comment by kaih1994** [comment]
I am doing this api, and what i first doing is to make sure the randomAlgorithm work. Next step, I will make the greedyAlgorithm work either.

**Comment by Vino4** [comment]
This is an example of how to use ImmutableJS to easily create the true and false array on ambiguous answers:
```
        import {Set} from 'immutable';
        
        let rui_question3_answers = ['Chicken'];

        let test = Set(rui_question3_answers);

        let allAnswers = Set([]);

        allAnswers = allAnswers.add('Chicken');

        allAnswers = allAnswers.add('Potatoe');

        allAnswers = allAnswers.add('Potatoe');

        console.log(allAnswers.toArray()); // ["Chicken", "Potatoe"]

        console.log(rui_question3_answers); //["Chicken"]

        allAnswers.forEach((answer) => {

            console.log('Rui has ' + answer + ': ' +test.has(answer)); 

        }); // Rui has Chicken: true
            // Rui has Potatoe: false
```

**Comment by kaih1994** [comment]
Now the randomAlgorithm works. 

API:
```
GET
 {server address}/api/activities/:activityId/participants/regroup/randomAlgorithm
```

**Comment by kaih1994** [comment]
The greedyAlgorithm works.
API:
```
GET
{server address}/api/activities/:activityId/participants/regroup/greedyAlgorithm
```

**Comment by kaih1994** [comment]
@Vino4 @lightertu I have made some tests in back end. Can you do some test in front end to see if it works?

**Comment by kaih1994** [comment]
My changes is in my branch, hasn't merge to master

**Comment by kaih1994** [comment]
Now the changes is in the masters. Check it!

**Comment by lightertu** [comment]
@kaih1994  is it done?

**Comment by kaih1994** [comment]
Yes. But I think we need to try it in the front end. If it passed, then we can close this issue.

**Comment by lightertu** [comment]
Good job guys
