### ISSUE TITLE
New Participants Group Assignments after group capacity is updated

### ISSUE THREAD

**Issue by lightertu** [lightertu/TeamDivider#68]
we need to consider the fact that, say, when the user changed the group size from 10 to 5, some groups will disappear, and we need to handle this case.

**Comment by kaih1994** [comment]
I have done it and give some basic tests. Try it in Front End!

**Comment by Vino4** [comment]
Tested this on the front end. Works great. Added error message on the front end to let the user know. see #79 Thanks @kaih1994
