### ISSUE TITLE
groups disappear and you can't put people back

### ISSUE THREAD

**Issue by Vino4** [lightertu/TeamDivider#72]
After you took all people out of group, the groups disappears, can't put them back in.
If no one is grouped no groups show up
@Lebonesco

**Comment by Lebonesco** [comment]
@Vino4 could you give more clarification on this? I'm pulling people out of groups but the groups are still there? Thanks.

**Comment by lightertu** [comment]
@Lebonesco Let me and @Vino4 handle this for now. We will let you know if we need to do anything.
