### ISSUE TITLE
SERVER_URL

### ISSUE THREAD

**Issue by Vino4** [lightertu/TeamDivider#73]
the server url is hard-coded into every axios instance. I used bash to change all occurrences to make it work on the demo server. However, this should be a config file.

**Comment by lightertu** [comment]
We need to setup a global variable as the server url

**Comment by Vino4** [comment]
I don't think there is a need for this anymore. I replaced all hardcoded URLs with window.location.host which has the sever's domain-name and port, it works very well with any server domain and port without the need for config :)
